[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "AwYxen6oaiLQk2VjPkw7CGUupKWCFkAFALGgw1LdxmA5"

[programs.testnet]
contract = "HKvDpbKfjDmyAwKayc4hewRZdMBgdLKVXgNpLFzfjEn9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# [provider]
# cluster = "https://api.testnet.solana.com"
# wallet = "~/.config/solana/testnet.json"
# timeout = 120000 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
