[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "HKvDpbKfjDmyAwKayc4hewRZdMBgdLKVXgNpLFzfjEn9"

[programs.testnet]
contract = "HKvDpbKfjDmyAwKayc4hewRZdMBgdLKVXgNpLFzfjEn9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "~/.config/solana/testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
